#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import agent
import agent.tasks

# Find default traefik instance for current node
default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

# Configure traefik virtual host
response = agent.tasks.run(
    agent_id=default_traefik_id,
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'],
        'url': f'http://127.0.0.1:{os.environ["TCP_PORT"]}',
        'host': os.environ["TRAEFIK_HOST"],
        'lets_encrypt': os.environ["TRAEFIK_LETS_ENCRYPT"] == True,
        'http2https': os.environ["TRAEFIK_HTTP2HTTPS"] == True
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)
